import { StyleSheet, Platform } from 'react-native'
import { FONT, SPACING } from '../constants/theme'

export const makeStyles = (theme) => StyleSheet.create({
  fullCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.color.surface,
  },
  container: {
    flexGrow: 1,
    backgroundColor: theme.color.surface,
    paddingTop: SPACING.md,
    paddingBottom: SPACING.xl,
    gap: SPACING.sm,
  },
  containerTablet: {
    maxWidth: 600,
    alignSelf: 'center',
    width: '100%',
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.md,
    marginTop: SPACING.xs,
  },
  headerTitle: {
    fontWeight: '900',
    color: theme.color.textPrimary,
  },

  sectionLabel: {
    fontSize: FONT.small,
    fontWeight: '800',
    color: theme.color.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: SPACING.sm,
    marginBottom: SPACING.xs,
  },

  summaryCard: {
    backgroundColor: theme.color.surfaceSubtle,
    borderRadius: theme.radius.md,
    padding: SPACING.md,
    gap: SPACING.xs,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: SPACING.sm,
    paddingVertical: 4,
  },
  summaryItemName: {
    flex: 1,
    fontSize: FONT.regular,
    color: theme.color.textPrimary,
    fontWeight: '600',
  },
  summaryItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  summaryQty: {
    fontSize: FONT.small,
    color: theme.color.textMuted,
    fontWeight: '600',
    minWidth: 28,
    textAlign: 'right',
  },
  summarySubtotal: {
    fontSize: FONT.regular,
    fontWeight: '700',
    color: theme.color.textPrimary,
    minWidth: 72,
    textAlign: 'right',
  },
  totalDivider: {
    height: 1,
    backgroundColor: theme.color.border,
    marginVertical: SPACING.xs,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: FONT.medium,
    fontWeight: '700',
    color: theme.color.textSecondary,
  },
  totalAmount: {
    fontSize: FONT.large,
    fontWeight: '900',
    color: theme.color.textPrimary,
  },

  addressCard: {
    backgroundColor: theme.color.surfaceSubtle,
    borderRadius: theme.radius.md,
    padding: SPACING.md,
    gap: SPACING.sm,
  },
  addressRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
    alignItems: 'flex-start',
  },
  input: {
    borderWidth: 1.5,
    borderColor: theme.color.border,
    borderRadius: theme.radius.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: Platform.OS === 'ios' ? 14 : 12,
    color: theme.color.textPrimary,
    backgroundColor: theme.color.surface,
  },
  inputError: {
    borderColor: theme.color.error,
  },
  errorText: {
    fontSize: FONT.small,
    color: theme.color.error,
    fontWeight: '600',
    marginTop: -SPACING.xs,
  },

  apiErrorBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.xs,
    backgroundColor: theme.color.accentSubtle,
    borderRadius: 10,
    padding: SPACING.sm,
  },
  apiErrorText: {
    flex: 1,
    fontSize: FONT.small,
    color: theme.color.error,
    fontWeight: '600',
    lineHeight: 18,
  },

  payButton: {
    backgroundColor: theme.color.accent,
    paddingVertical: 16,
    borderRadius: theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: SPACING.md,
    minHeight: theme.button.minHeight + 10,
  },
  payButtonDisabled: {
    backgroundColor: theme.color.textMuted,
  },
  payButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
  },
  payButtonText: {
    color: theme.color.onAccent,
    fontSize: FONT.medium,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  secureNote: {
    textAlign: 'center',
    fontSize: 12,
    color: theme.color.textMuted,
    marginTop: SPACING.xs,
  },

  couponRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
    alignItems: 'center',
  },
  couponInput: {
    flex: 1,
  },
  couponApplyButton: {
    backgroundColor: theme.color.accent,
    paddingVertical: 12,
    paddingHorizontal: SPACING.md,
    borderRadius: theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
    minHeight: theme.button.minHeight,
  },
  couponApplyText: {
    color: theme.color.onAccent,
    fontWeight: '700',
    fontSize: FONT.small,
  },
  couponAppliedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.color.surfaceSubtle,
    borderRadius: theme.radius.md,
    paddingHorizontal: SPACING.md,
    paddingVertical: 12,
  },
  couponAppliedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
  },
  couponAppliedText: {
    fontSize: FONT.small,
    fontWeight: '700',
    color: theme.color.success,
  },
  couponErrorText: {
    fontSize: FONT.small,
    color: theme.color.error,
    fontWeight: '600',
    marginTop: -SPACING.xs,
  },
  discountLabel: {
    color: theme.color.success,
  },
  discountAmount: {
    color: theme.color.success,
  },

  resultIconCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: theme.color.success,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: SPACING.lg,
  },
  resultTitle: {
    fontSize: FONT.large,
    fontWeight: '900',
    color: theme.color.textPrimary,
    textAlign: 'center',
    marginBottom: SPACING.sm,
  },
  resultSubtitle: {
    fontSize: FONT.regular,
    color: theme.color.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: SPACING.xl,
    paddingHorizontal: SPACING.md,
  },
  processingTitle: {
    fontSize: FONT.large,
    fontWeight: '900',
    color: theme.color.textPrimary,
    marginTop: SPACING.lg,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  processingSubtitle: {
    fontSize: FONT.regular,
    color: theme.color.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: SPACING.md,
  },
  primaryButton: {
    backgroundColor: theme.color.accent,
    paddingVertical: 14,
    paddingHorizontal: SPACING.xl,
    borderRadius: theme.radius.md,
    alignItems: 'center',
    width: '100%',
    maxWidth: 320,
    minHeight: theme.button.minHeight,
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: theme.color.onAccent,
    fontSize: FONT.medium,
    fontWeight: '800',
  },
  ghostButton: {
    marginTop: SPACING.sm,
    paddingVertical: 14,
    paddingHorizontal: SPACING.xl,
    borderRadius: theme.radius.md,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.color.border,
    width: '100%',
    maxWidth: 320,
    minHeight: theme.button.minHeight,
    justifyContent: 'center',
  },
  ghostButtonText: {
    color: theme.color.textSecondary,
    fontSize: FONT.medium,
    fontWeight: '700',
  },
})