import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../constants/colors";
import { SPACING, FONT } from "../constants/theme";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.white },
  fullCenter: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.white, gap: SPACING.md },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: SPACING.md, paddingBottom: SPACING.sm },
  title: { fontWeight: '900', color: COLORS.textPrimary },
  filterScroll: { flexGrow: 0, marginBottom: SPACING.sm },
  filterContent: { flexDirection: 'row', gap: SPACING.xs, paddingBottom: 4 },
  filterChip: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: 999, borderWidth: 1.5, borderColor: COLORS.divider, backgroundColor: COLORS.white },
  filterChipText: { fontSize: 13, fontWeight: '600', color: COLORS.textSecondary },
  filterChipTextActive: { color: COLORS.white, fontWeight: '700' },
  listContainer: { flex: 1 },
  listContainerTablet: { maxWidth: 800, alignSelf: 'center', width: '100%' },
  listContent: { paddingBottom: SPACING.xl, paddingTop: SPACING.xs },
  orderCard: { backgroundColor: COLORS.background, borderRadius: 16, padding: SPACING.md, marginBottom: SPACING.sm, gap: 4 },
  orderCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  orderCardBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 2 },
  orderId: { fontSize: FONT.small, color: COLORS.textSecondary, fontWeight: '600', letterSpacing: 0.3 },
  orderDate: { fontSize: 12, color: COLORS.textMuted, fontWeight: '500' },
  orderTotal: { fontSize: FONT.medium, fontWeight: '900', color: COLORS.textPrimary },
  badge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999 },
  badgeSmall: { paddingHorizontal: 8, paddingVertical: 4 },
  badgeText: { color: COLORS.white, fontSize: 12, fontWeight: '700' },
  badgeTextSmall: { fontSize: 11 },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: SPACING.sm, paddingHorizontal: SPACING.xl },
  emptyTitle: { fontSize: FONT.medium, fontWeight: '800', color: COLORS.textPrimary },
  emptyText: { fontSize: FONT.regular, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 22 },
  actionButton: { backgroundColor: COLORS.primary, paddingVertical: 12, paddingHorizontal: SPACING.lg, borderRadius: 12, marginTop: SPACING.xs },
  actionButtonText: { color: COLORS.white, fontWeight: '800', fontSize: FONT.regular },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: SPACING.md, paddingVertical: SPACING.sm, borderBottomWidth: 1, borderBottomColor: COLORS.divider },
  modalCloseBtn: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: COLORS.background },
  modalTitle: { fontSize: FONT.medium, fontWeight: '800', color: COLORS.textPrimary },
  modalBody: { padding: SPACING.lg, gap: SPACING.md, paddingBottom: SPACING.xl },
  detailHero: { alignItems: 'flex-start', gap: SPACING.xs, paddingBottom: SPACING.md, borderBottomWidth: 1, borderBottomColor: COLORS.divider },
  detailOrderId: { fontSize: FONT.large, fontWeight: '900', color: COLORS.textPrimary, letterSpacing: 0.5 },
  detailMeta: { fontSize: FONT.small, color: COLORS.textMuted, fontWeight: '500' },
  detailSection: { gap: SPACING.xs },
  sectionLabel: { fontSize: 11, fontWeight: '800', color: COLORS.textMuted, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 2 },
  detailSectionCard: { flexDirection: 'row', alignItems: 'flex-start', gap: SPACING.xs, backgroundColor: COLORS.background, borderRadius: 10, padding: SPACING.sm },
  detailText: { flex: 1, fontSize: FONT.regular, color: COLORS.textPrimary, lineHeight: 20 },
  detailItem: { backgroundColor: COLORS.background, borderRadius: 12, padding: SPACING.sm, gap: 6 },
  detailItemNameRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: SPACING.xs },
  detailItemPlainName: { flex: 1, fontSize: FONT.regular, fontWeight: '700', color: COLORS.textPrimary },
  detailItemRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  detailItemMeta: { fontSize: FONT.small, color: COLORS.textSecondary },
  detailItemSubtotal: { fontSize: FONT.regular, fontWeight: '800', color: COLORS.textPrimary },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: COLORS.divider, borderBottomWidth: 1, borderBottomColor: COLORS.divider, paddingVertical: SPACING.md },
  totalLabel: { fontSize: FONT.medium, color: COLORS.textSecondary, fontWeight: '600' },
  totalAmount: { fontSize: FONT.large, fontWeight: '900', color: COLORS.textPrimary },
  
  // Historial
  historyRow: { flexDirection: 'row', alignItems: 'flex-start', gap: SPACING.sm, paddingVertical: SPACING.xs },
  historyDot: { width: 10, height: 10, borderRadius: 5, marginTop: 5, flexShrink: 0 },
  historyStatus: { fontSize: FONT.regular, fontWeight: '700', color: COLORS.textPrimary },
  historyDate: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
  
  // Rechazados
  orderCardRejected: { borderWidth: 1.5, borderColor: '#fca5a5', backgroundColor: '#fff8f8' },
  orderCardRejectedHint: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: SPACING.xs, paddingTop: SPACING.xs, borderTopWidth: 1, borderTopColor: '#fca5a5' },
  orderCardRejectedHintText: { fontSize: 12, color: COLORS.error, fontWeight: '600' },
  rejectedBanner: { backgroundColor: '#fff0f0', borderRadius: 14, borderWidth: 1.5, borderColor: '#fca5a5', padding: SPACING.md, gap: SPACING.sm },
  rejectedBannerTop: { flexDirection: 'row', alignItems: 'center', gap: SPACING.xs },
  rejectedBannerTitle: { fontSize: FONT.medium, fontWeight: '800', color: COLORS.error },
  rejectedBannerText: { fontSize: FONT.small, color: '#b91c1c', lineHeight: 20 },
  rejectedBannerBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: SPACING.xs, borderWidth: 1.5, borderColor: COLORS.error, borderRadius: 10, paddingVertical: 10, paddingHorizontal: SPACING.md, backgroundColor: COLORS.white },
  rejectedBannerBtnText: { fontSize: FONT.small, fontWeight: '800', color: COLORS.error },
  
  trackingCode: { fontWeight: '700', letterSpacing: 0.5, fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  confirmDeliveryBtn: { backgroundColor: COLORS.success, paddingVertical: 12, paddingHorizontal: SPACING.lg, borderRadius: 10, alignItems: 'center', alignSelf: 'stretch', marginTop: SPACING.xs, minHeight: 44, justifyContent: 'center' },
  confirmDeliveryBtnDisabled: { opacity: 0.6 },
  confirmDeliveryBtnText: { color: COLORS.white, fontSize: FONT.regular, fontWeight: '800' },

  // Estilos de los paquetes
  packageCard: { marginBottom: 20, padding: 15, backgroundColor: COLORS.white, borderRadius: 8, borderWidth: 1, borderColor: COLORS.divider },
  packageHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  packageTitle: { fontWeight: 'bold', fontSize: FONT.medium, color: COLORS.textPrimary }
})